#ifndef	FLATMAPMARKERSSSE_VERSION_INCLUDED
#define FLATMAPMARKERSSSE_VERSION_INCLUDED

#define MAKE_STR_HELPER(x) #x
#define MAKE_STR(x) MAKE_STR_HELPER(x)

#define FLATMAPMARKERSSSE_VERSION_MAJOR		1
#define FLATMAPMARKERSSSE_VERSION_MINOR		0
#define FLATMAPMARKERSSSE_VERSION_PATCH		0
#define FLATMAPMARKERSSSE_VERSION_BETA		0
#define FLATMAPMARKERSSSE_VERSION_VERSTRING	MAKE_STR(FLATMAPMARKERSSSE_VERSION_MAJOR) "." MAKE_STR(FLATMAPMARKERSSSE_VERSION_MINOR) "." MAKE_STR(FLATMAPMARKERSSSE_VERSION_PATCH) "." MAKE_STR(FLATMAPMARKERSSSE_VERSION_BETA)

#endif
