#ifndef	FLTM_VERSION_INCLUDED
#define FLTM_VERSION_INCLUDED

#define MAKE_STR_HELPER(x) #x
#define MAKE_STR(x) MAKE_STR_HELPER(x)

#define FLTM_VERSION_MAJOR		1
#define FLTM_VERSION_MINOR		1
#define FLTM_VERSION_PATCH		1
#define FLTM_VERSION_BETA		0
#define FLTM_VERSION_VERSTRING	MAKE_STR(FLTM_VERSION_MAJOR) "." MAKE_STR(FLTM_VERSION_MINOR) "." MAKE_STR(FLTM_VERSION_PATCH) "." MAKE_STR(FLTM_VERSION_BETA)

#endif
